project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "EDAV Group 4: Shadows in the City -- Analyzing NYPD Arrest Data to Illuminate Crime Patterns in NYC"
  author:
    - Jiaheng Dai (jd4136)
    - Zhiqi Ma (zm2467)
  repo-url: https://github.com/jdai0/EDAV_Final_Project_Group4.git
  date: today
  page-footer:
    left: "© 2024 EDAV Group 4"
    right: "Created by ZM and JD"
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: Sandstone
    highlight-style: solarized-light
    code-fold: true
    toc: true                
    toc-depth: 2



