project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "EDAV Final Project Group 4"
  author:
    - Jiaheng Dai (jd4136)
    - Zhiqi Ma (zm2467)
  repo-url: https://github.com/jdai0/EDAV_Final_Project_Group4.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


