# Introduction

On November 8th, a man opened fire on an NYC subway, shooting the victim in the legs. The incident happened on the Upper West, not far from where we lived. Just 10 days later, three people were killed in random stabbing spree. The murderer, covered in blood, walked freely in the bustling streets in Manhattan before being arrested. We live in a city that riffles with opportunities and danger at the same time. As data science students in NYC, both our own safety and the community we share are deeply intertwined with issues of public safety. In this project, we attempt to conduct an Exploratory Data Analysis (EDA) on crimes in NYC as our means to raise awareness and contribute to the community.

We identified NYPD Arrest Data as our main data source, which includes information such as the type of crime, location, time, and suspect demographics. Although many crimes are deep-rooted, requiring massive investment and sacrifices to address, EDA could still yield valuable insight. By exploring social-economic correlations behind crimes, EDA could serve as a fundamental step for interventions and policy changes.

We proposed the following research questions:

What are the most common types of arrests in NYC, and how are they distributed across different categories?

How do arrests vary geographically across the boroughs of NYC?

What are the demographic profiles of individuals arrested, including age, gender, and race distributions?

How do arrest patterns change over time, and what temporal trends can be observed?

